Repository ryanntannn/dicerealm, pull requests merged in 2025-04, with the labels that each got.

#46 Feat: Combat transition
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/dicerealmandroid/DicerealmClient.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CombatScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/DialogScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/game/GameStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatSequence.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/game/dialog/DialogStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/player/PlayerStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/room/RoomRepo.java
  android/app/src/main/res/layout/activity_combat_screen.xml
  android/app/src/main/res/values/styles.xml
  core/lib/src/main/java/com/dicerealm/core/dialogue/SkillCheck.java
Labels: enhancement

#50 Feat/combat-system/level-system
  core/lib/src/main/java/com/dicerealm/core/combat/CombatResult.java
  core/lib/src/main/java/com/dicerealm/core/combat/managers/CombatManager.java
  core/lib/src/main/java/com/dicerealm/core/combat/managers/MonsterAI.java
  core/lib/src/main/java/com/dicerealm/core/dialogue/DialogueManager.java
  core/lib/src/main/java/com/dicerealm/core/handler/CombatTurnActionHandler.java
  core/lib/src/main/java/com/dicerealm/core/item/Weapon.java
  core/lib/src/main/java/com/dicerealm/core/room/Room.java
  core/lib/src/main/java/com/dicerealm/core/room/RoomContext.java
  core/lib/src/main/java/com/dicerealm/core/skills/Fireball.java
  core/lib/src/main/java/com/dicerealm/core/skills/Skill.java
  core/lib/src/test/java/com/dicerealm/core/combat/ActionManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/combat/CombatDamageTest.java
  core/lib/src/test/java/com/dicerealm/core/combat/CombatManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/dialogue/DialogueManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/handler/UpdatePlayerDetailsHandlerTest.java
Labels: enhancement

#49 Feat/combat-system/monsterai
  core/lib/src/main/java/com/dicerealm/core/combat/CombatResult.java
  core/lib/src/main/java/com/dicerealm/core/combat/managers/ActionManager.java
  core/lib/src/main/java/com/dicerealm/core/combat/managers/CombatManager.java
  core/lib/src/main/java/com/dicerealm/core/combat/managers/LevelManager.java
  core/lib/src/main/java/com/dicerealm/core/combat/managers/MonsterAI.java
  core/lib/src/main/java/com/dicerealm/core/dialogue/DialogueManager.java
  core/lib/src/main/java/com/dicerealm/core/dice/MultiDice.java
  core/lib/src/main/java/com/dicerealm/core/handler/CombatTurnActionHandler.java
  core/lib/src/main/java/com/dicerealm/core/item/Weapon.java
  core/lib/src/main/java/com/dicerealm/core/monster/Monster.java
  core/lib/src/main/java/com/dicerealm/core/room/Room.java
  core/lib/src/main/java/com/dicerealm/core/room/RoomContext.java
  core/lib/src/main/java/com/dicerealm/core/room/RoomState.java
  core/lib/src/main/java/com/dicerealm/core/skills/Fireball.java
  core/lib/src/main/java/com/dicerealm/core/skills/Skill.java
  core/lib/src/test/java/com/dicerealm/core/combat/ActionManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/combat/CombatDamageTest.java
  core/lib/src/test/java/com/dicerealm/core/combat/CombatManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/dialogue/DialogueManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/handler/UpdatePlayerDetailsHandlerTest.java
Labels: enhancement

#51 feat: Creates and Integrates Level Manager
  core/lib/src/main/java/com/dicerealm/core/combat/managers/LevelManager.java
  core/lib/src/main/java/com/dicerealm/core/combat/managers/MonsterGenerator.java
  core/lib/src/main/java/com/dicerealm/core/combat/systems/RoomStrengthCalculator.java
  core/lib/src/main/java/com/dicerealm/core/command/levelling/SkillSelectionCommand.java
  core/lib/src/main/java/com/dicerealm/core/command/levelling/SkillSelectionCompleteCommand.java
  core/lib/src/main/java/com/dicerealm/core/command/levelling/SkillSelectionResponseCommand.java
  core/lib/src/main/java/com/dicerealm/core/dialogue/DialogueManager.java
  core/lib/src/main/java/com/dicerealm/core/handler/CombatTurnActionHandler.java
  core/lib/src/main/java/com/dicerealm/core/handler/SkillSelectionResponseHandler.java
  core/lib/src/main/java/com/dicerealm/core/monster/Monster.java
  core/lib/src/main/java/com/dicerealm/core/room/Room.java
  core/lib/src/main/java/com/dicerealm/core/room/RoomContext.java
  core/lib/src/main/java/com/dicerealm/core/room/RoomState.java
  core/lib/src/main/java/com/dicerealm/core/skills/SkillSelectionProcessor.java
  core/lib/src/main/java/com/dicerealm/core/skills/SkillSelectionResult.java
  core/lib/src/main/java/com/dicerealm/core/skills/SkillsRepository.java
  core/lib/src/test/java/com/dicerealm/core/combat/LevelManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/dialogue/DialogueManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/handler/UpdatePlayerDetailsHandlerTest.java
Labels: enhancement

#57 Feat/combat-system/monstergeneration
  core/lib/src/main/java/com/dicerealm/core/combat/managers/MonsterGenerator.java
  core/lib/src/main/java/com/dicerealm/core/combat/systems/WeaponGenerator.java
  core/lib/src/main/java/com/dicerealm/core/dialogue/DialogueManager.java
  core/lib/src/main/java/com/dicerealm/core/item/weapons/AxeFactory.java
  core/lib/src/main/java/com/dicerealm/core/item/weapons/BowFactory.java
  core/lib/src/main/java/com/dicerealm/core/item/weapons/SpearFactory.java
  core/lib/src/main/java/com/dicerealm/core/item/weapons/StaffFactory.java
  core/lib/src/main/java/com/dicerealm/core/item/weapons/SwordFactory.java
  core/lib/src/test/java/com/dicerealm/core/combat/LevelManagerTest.java
  core/lib/src/test/java/com/dicerealm/core/combat/MonsterGeneratorTest.java
Labels: enhancement

#61 feat: Adds Default Skills to all Players
  core/lib/src/main/java/com/dicerealm/core/entity/ClassStats.java
  core/lib/src/main/java/com/dicerealm/core/player/PresetPlayerFactory.java
  core/lib/src/main/java/com/dicerealm/core/skills/SkillsRepository.java
Labels: enhancement

#62 Feat/android/general game logic
  android/app/src/main/java/com/example/dicerealmandroid/DicerealmClient.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CharacterScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CombatScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/DialogScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/game/dialog/Dialog.java
  android/app/src/main/java/com/example/dicerealmandroid/game/dialog/DialogStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/player/PlayerRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/player/PlayerStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/room/RoomRepo.java
  android/app/src/main/res/layout/activity_dialog_screen.xml
Labels: bug, enhancement

#65 Feat/combat-system/consumables
  core/lib/src/main/java/com/dicerealm/core/combat/managers/ActionManager.java
  core/lib/src/test/java/com/dicerealm/core/combat/ActionManagerTest.java
Labels: enhancement

#63 feat/androidUI_combat
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/dicerealmandroid/DicerealmClient.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CombatScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatSequence.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatTurnModal.java
  android/app/src/main/java/com/example/dicerealmandroid/game/dialog/DialogDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/player/PlayerRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/player/PlayerStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/recyclerview/CardAdapter.java
  android/app/src/main/java/com/example/dicerealmandroid/recyclerview/InventoryCardAdapter.java
  android/app/src/main/java/com/example/dicerealmandroid/recyclerview/SelectListener.java
  android/app/src/main/java/com/example/dicerealmandroid/recyclerview/SpellCardAdapter.java
  android/app/src/main/java/com/example/dicerealmandroid/room/RoomRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/util/Serialization.java
  android/app/src/main/res/drawable/bold_cell_border.xml
  android/app/src/main/res/drawable/cell_border.xml
  android/app/src/main/res/drawable/enemyicon.png
  android/app/src/main/res/drawable/hearticon.xml
  android/app/src/main/res/layout/activity_combat_screen.xml
  core/lib/src/main/java/com/dicerealm/core/combat/systems/InitiativeResult.java
  core/lib/src/main/java/com/dicerealm/core/command/combat/CombatStartTurnCommand.java
Labels: bug, enhancement

#70 Fix: Player Enemies details update
  android/app/src/main/java/com/example/dicerealmandroid/DicerealmClient.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CombatScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/DialogScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/player/PlayerRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/room/RoomRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/util/Serialization.java
  android/app/src/main/res/layout/activity_combat_screen.xml
  core/lib/src/main/java/com/dicerealm/core/entity/Entity.java
  core/lib/src/main/java/com/dicerealm/core/util/graph/Edge.java
  core/lib/src/main/java/com/dicerealm/core/util/graph/Graph.java
Labels: bug

#71 Feat/android/location display
  android/app/src/main/java/com/example/dicerealmandroid/DicerealmClient.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CombatScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/DialogScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/adapters/InventoryDialogAdapter.java
  android/app/src/main/java/com/example/dicerealmandroid/adapters/LocationAdapter.java
  android/app/src/main/java/com/example/dicerealmandroid/fragments/InventoryDialogFragment.java
  android/app/src/main/java/com/example/dicerealmandroid/game/GameDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/game/GameRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/game/GameStateHolder.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/game/dialog/DialogDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/game/dialog/DialogRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/player/PlayerDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/player/wrapper/PlayerInventoryWrapper.java
  android/app/src/main/java/com/example/dicerealmandroid/room/RoomDataSource.java
  android/app/src/main/java/com/example/dicerealmandroid/room/RoomRepo.java
  android/app/src/main/java/com/example/dicerealmandroid/util/Serialization.java
  android/app/src/main/res/drawable/location.png
  android/app/src/main/res/layout/activity_dialog_screen.xml
  android/app/src/main/res/layout/location_dropdown.xml
  android/app/src/main/res/layout/location_dropdown_layout.xml
Labels: bug, enhancement

#75 feat: Combat turns design
  android/app/src/main/java/com/example/dicerealmandroid/DicerealmClient.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CharacterScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/activity/CombatScreen.java
  android/app/src/main/java/com/example/dicerealmandroid/game/combat/CombatRepo.java
  android/app/src/main/res/layout/activity_combat_screen.xml
Labels: enhancement
